.TH WITCHCRAFT "1" "August 2016" "Witchcraft Compiler Collection (WCC)" "User Commands"
.SH NAME
Witchcraft \- manual page for Witchcraft Core Compiler
.SH SYNOPSIS
.B wcc
[\fIoptions\fR] \fIfile\fR
.SH DESCRIPTION
options:
.TP
\fB\-o\fR, \fB\-\-output\fR
<output file>
.TP
\fB\-m\fR, \fB\-\-march\fR
<architecture>
.TP
\fB\-e\fR, \fB\-\-entrypoint\fR
<0xaddress>
.TP
\fB\-i\fR, \fB\-\-interpreter\fR
<interpreter>
.TP
\fB\-p\fR, \fB\-\-poison\fR
<poison>
.HP
\fB\-s\fR, \fB\-\-shared\fR
.HP
\fB\-c\fR, \fB\-\-compile\fR
.HP
\fB\-S\fR, \fB\-\-static\fR
.HP
\fB\-x\fR, \fB\-\-strip\fR
.HP
\fB\-X\fR, \fB\-\-sstrip\fR
.HP
\fB\-E\fR, \fB\-\-exec\fR
.HP
\fB\-C\fR, \fB\-\-core\fR
.HP
\fB\-O\fR, \fB\-\-original\fR
.HP
\fB\-D\fR, \fB\-\-disasm\fR
.HP
\fB\-d\fR, \fB\-\-debug\fR
.HP
\fB\-h\fR, \fB\-\-help\fR
.HP
\fB\-v\fR, \fB\-\-verbose\fR
.HP
\fB\-V\fR, \fB\-\-version\fR
.SH "SEE ALSO"
The full documentation of the
.B Witchcraft Compiler Collection
is available online at https://github.com/endrazine/wcc/wiki

