.TH WCCH "1" "April 2017" "Witchcraft Compiler Collection" "User Commands"
.SH NAME
wcch \- generate C headers from executable files
.SH SYNOPSIS
.B wcch
\fIfile\fR
.SH DESCRIPTION
wcch is part of the Witchcraft Compiler Collection.
.TP
Generate C header from the binary file passed as argument.
.SH EXAMPLES
.TP
wcch /bin/ls
Create a C header file from the binary executable /bin/ls
.SH NOTES
The Witcraft Compiler Collection is a set of reverse engineering tools.
.SH AUTHOR
Written by endrazine (Jonathan Brossard)
.SH "REPORTING BUGS"
Witchcraft Compiler Collection online bug tracker: <https://github.com/endrazine/wcc/issues>
.SH COPYRIGHT
Copyright Jonathan Brossard
.br
License : MIT and BSD Licenses. See <https://github.com/endrazine/wcc/blob/master/LICENSE>.
.br
.SH "SEE ALSO"
\fBwsh\fP(1),
\fBwcc\fP(1),
\fBwld\fP(1),
\fBwldd\fP(1)
.PP
The full documentation of the
.B Witchcraft Compiler Collection
is available online at https://github.com/endrazine/wcc/wiki

