.TH WITCHCRAFT "1" "August 2016" "Witchcraft Compiler Collection (WCC)" "User Commands"
.SH NAME
Witchcraft \- manual page for Witchcraft Linker
.SH SYNOPSIS
.B wld
[\fIoptions\fR] \fIfile\fR
.SH DESCRIPTION
The Witchcraft Linker
.PP
options:
.TP
\fB\-libify\fR
Set Class to ET_DYN in input ELF file.
.PP
Usage: \fI/usr/bin/wld\fP [options] file
.PP
options:
.TP
\fB\-libify\fR
Set Class to ET_DYN in input ELF file.
.SH "SEE ALSO"
The full documentation of the
.B Witchcraft Compiler Collection
is available online at https://github.com/endrazine/wcc/wiki

