.TH WLD "1" "April 2017" "Witchcraft Compiler Collection" "User Commands"
.SH NAME
wld \- transform executables into shared libaries
.SH SYNOPSIS
.B wld
\fI-libify\fR [\fI-noinit\fR] \fIfile\fR
.SH DESCRIPTION
The Witchcraft Linker is part of the Witchcraft Compiler Collection.
.PP
Options:
.TP
\fB\-libify\fR
Libifies input ELF executable into a shared library.
.TP
\fB\-noinit\fR
Ignore constructors and desctructors in output library.
.SH EXAMPLES
.TP
cp /bin/cat /tmp && wld -libify /tmp/cat
Copy the executable /bin/cat to /tmp and transform it into a shared library.
.SH NOTES
wld alters the file passed as argument.
.br
The Witcraft Compiler Collection is a set of reverse engineering tools.
.SH AUTHOR
Written by endrazine (Jonathan Brossard)
.SH "REPORTING BUGS"
Witchcraft Compiler Collection online bug tracker: <https://github.com/endrazine/wcc/issues>
.SH COPYRIGHT
Copyright Jonathan Brossard
.br
License: MIT and BSD Licenses. See <https://github.com/endrazine/wcc/blob/master/LICENSE>.
.br
.SH "SEE ALSO"
\fBwsh\fP(1),
\fBwcc\fP(1),
\fBwldd\fP(1),
\fBwcch\fP(1)
.PP
The full documentation of the
.B Witchcraft Compiler Collection
is available online at https://github.com/endrazine/wcc/wiki
