#
# This file is part of the Witchcraft Compiler Collection
# Copyright 2016-2022 Jonathan Brossard
#
# Homepage: https://github.com/endrazine/wcc/
#
# This file is licensed under MIT License.
#

all::
	cd apache2 && make
	cd  sshd && make
	cd  sshd2 && make

clean:
	cd apache2 && make clean
	cd  sshd && make clean
	cd  sshd2 && make clean


