all::
	cd wcc && make
	cd wld && make
	cd wsh && make
	cd tools && make
clean:
	cd wcc && make clean
	cd wld && make clean
	cd wsh && make clean
	cd tools && make clean

install:
	cd wcc && make install
	cd wld && make install
	cd wsh && make install
	cd tools && make install

uninstall:
	cd wcc && make uninstall
	cd wld && make uninstall
	cd wsh && make uninstall
	cd tools && make uninstall

