#
# This file is part of the Witchcraft Compiler Collection
# Copyright 2016-2025 Jonathan Brossard
#
# Homepage: https://github.com/endrazine/wcc/
#
# This file is licensed under MIT License.
#

all::
	cp wcch ../../bin/
test:

clean:
	rm ../../bin/wcch -f

install:
	cp wcch $(DESTDIR)/usr/bin/wcch

uninstall:
	rm $(DESTDIR)/usr/bin/wcch -f



