#!/bin/sh
#
# wlld : This file is part of the Witchcraft Compiler Collection
#
# Copyright : Jonathan Brossard - endrazine@gmail.com
#
# This file is licensed under the MIT license
#
# version 0.01 Sun Jul 17 19:25:18 PDT 2016
#
#

usage() {
	echo "Usage: $0 </path/to/bin>"
	echo ""
	echo "  Returns libraries to be passed to gcc to relink this application."
	echo ""
	exit 1
}

getlibs() {
	ldd "$1" | awk '/=> \// {sub(/\..*/, "", $1); sub(/^lib/, "-l", $1); printf("%s ", $1)}  END {print ""}'
}

if [ "$#" -ne 1 ]
then
	usage
fi

getlibs "$1"
